configuration:
- build-linux-1
- build-linux-2
- build-macos
- build-windows

for:
- matrix:
    only:
    - configuration: build-linux-1
  environment:
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    CI_TESTING_LINUX: Linux
    CI_TESTING_NUMBER: 1

- matrix:
    only:
    - configuration: build-linux-2
  environment:
    APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    CI_TESTING_LINUX: Linux
    CI_TESTING_NUMBER: 2

- matrix:
    only:
    - configuration: build-macos
  environment:
    APPVEYOR_BUILD_WORKER_IMAGE: macos
    CI_TESTING_MAC: macos

- matrix:
    only:
    - configuration: build-windows
  environment:
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CI_TESTING_WINDOWS: Windows

install:
- npm install

test_script:
- npm test

build: off
