image:
- Visual Studio 2017
- macos
- Ubuntu

for:
- matrix:
    only:
    - image: Visual Studio 2017
  environment:
    CI_TESTING_WINDOWS: Windows

- matrix:
    only:
    - image: macos
  environment:
    CI_TESTING_MAC: macOS

- matrix:
    only:
    - image: Ubuntu
  environment:
    CI_TESTING_LINUX: Linux
    matrix:
    - CI_TESTING_TASK_A_1: task_a_1
      CI_TESTING_TASK_A_2: task_a_2
    - CI_TESTING_TASK_B_1: task_b_1
      CI_TESTING_TASK_B_2: task_b_2

install:
- npm install

test_script:
- npm test

build: off
