environment:
- matrix:
  appveyor_build_worker_image: Ubuntu
  environment:
    CI_TESTING_LINUX: Linux
    CI_TESTING_NUMBER: 1

- matrix:
  appveyor_build_worker_image: Ubuntu
  environment:
    CI_TESTING_LINUX: Linux
    CI_TESTING_NUMBER: 2

- matrix:
  appveyor_build_worker_image: macos
  environment:
    CI_TESTING_MAC: macos

- matrix:
  appveyor_build_worker_image: Visual Studio 2017
  environment:
    CI_TESTING_WINDOWS: Windows

install:
- npm install

test_script:
- npm test

build: off
