configuration:
- build-a
- build-b
- build-c

image:
- Ubuntu

for:
- matrix:
    only:
    - configuration: build-a
  environment:
    CI_TESTING_BUILD: A

- matrix:
    only:
    - configuration: build-b
  environment:
    CI_TESTING_BUILD: B

- matrix:
    only:
    - configuration: build-c
  environment:
    CI_TESTING_BUILD: C

install:
- npm install

test_script:
- npm test

build: off
